add-recommendations v.1.0
myanotheraccount/java-filmorate pull request #7
Opened 2022-08-18 15:44 UTC by SergeiNazarkin

2022-08-19 06:18 UTC, myanotheraccount requested changes

2022-08-19 06:18 UTC, myanotheraccount commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/RecommendationDao.java
> +        final String sqlQueryFilmsID = "SELECT FILM_ID from LIKES where USER_ID = ?";
Этот запрос повторяется 3 раза, лучше вынести в отдельный метод и возвращать массив данных с результатом

2022-08-19 21:12 UTC, SergeiNazarkin commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/RecommendationDao.java
> +        final String sqlQueryFilmsID = "SELECT FILM_ID from LIKES where USER_ID = ?";
поправил

2022-08-20 06:39 UTC, myanotheraccount approved these changes

2022-08-20 14:26 UTC, damikhaylov commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmDaoImpl.java
> +    protected Film parseFilm(ResultSet rs, int rowNum) throws SQLException {
Не нашёл в итоговом варианте использование этого метода, требующего модификатора доступа protected — возможно, просто просмотрел. Если этот модификатор действительно не нужен, желательно вернуть private, чтобы класс не менялся.

2022-08-20 14:26 UTC, damikhaylov approved these changes

2022-08-22 15:53 UTC, merged